[workspace]
channels = ["conda-forge", "robostack-staging"]
name = "pruning_workspace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.11.*"
numpy = "1.26.4.*"
ros-humble-desktop-full = ">=0.10.0,<0.11"
colcon-core = ">=0.19.0,<0.20"
ros-humble-moveit = ">=2.5.7,<3"
gazebo = ">=11.15.1,<12"
ros-humble-gazebo-ros = ">=3.7.0,<4"
ros-humble-gazebo-ros-pkgs = ">=3.7.0,<4"
rosdep = ">=0.25.1,<0.26"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-humble-gazebo-ros2-control = ">=0.4.10,<0.5"
ros-humble-control-toolbox = ">=3.4.0,<4"
ros-humble-controller-manager = ">=2.47.0,<3"
ros-humble-moveit-servo = ">=2.5.7,<3"
ros-humble-hardware-interface = ">=2.47.0,<3"
ros-humble-controller-manager-msgs = ">=2.47.0,<3"
ros-humble-joint-trajectory-controller = ">=2.40.0,<3"
ros-humble-joint-state-broadcaster = ">=2.40.0,<3"
quaternion = ">=2024.0.8,<2025"
pip = ">=25.1.1,<26"
pyassimp = ">=5.2.5,<6"
colourmap = ">=1.1.21,<2"
ros-humble-geographic-msgs = ">=1.0.6,<2"
ros-humble-zstd-point-cloud-transport = ">=1.0.11,<2"
ros-humble-robot-localization = ">=3.5.3,<4"
ros-humble-diagnostic-updater = ">=4.0.0,<5"
opencv = ">=4.10.0,<5"
cuda = "12.6.*"
pycolmap = ">=3.11"
ninja = ">=1.12.1,<2"
matplotlib = ">=3.10.0,<4"

[pypi-options]
index-url = "https://pypi.org/simple"
no-build-isolation = ["fused-ssim"]
extra-index-urls = ["http://csse-maaratech1.canterbury.ac.nz:4040/maara/cstack/+simple/"]

[pypi-dependencies]
py-structs = ">=1.1.0,<4"
splat-viewer = { path = "src/splat-viewer", editable = true }
taichi-splatting = { path = "src/taichi-splatting", editable = true }
torch = { version = "==2.6.0", index = "https://download.pytorch.org/whl/cu126" }
torchvision = { version = ">=0.21.0", index = "https://download.pytorch.org/whl/cu126" }
fused-ssim = { git = "https://github.com/uc-vision/fused-ssim.git", rev = "613400e" }
small-gicp = "*"
open3d = ">=0.19.0,<0.20"

[system-requirements]
cuda = "12.1"
libc = { family = "glibc", version = "2.31" }