[project]
name = "foundation_stereo"
version = "1.0.0"
authors = [{ name = "Philip Stenger", email = "pst82@uclive.ac.nz" }]
description = "Stereo model"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.0.0",
    "opencv-python>=4.8.0",
    "numpy>=1.24.0",
    "open3d>=0.17.0",
    "omegaconf>=2.3.0",
    "imageio>=2.31.0",
    "beartype>=0.15.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

# [tool.setuptools]
# packages = ["FoundationStereo"]

[project.scripts]


[tool.pytest.ini_options]
filterwarnings = [
    # disable "UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor"
    "ignore::UserWarning"  
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.tasks]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]